### ISSUE TITLE
Error in example/wgas1.tped:1: invalid nucleotide value '0' at position 265

### ISSUE THREAD

**Issue by shadiakiki1986** [chponte/mpi3snp#7]
Hello. I tried to run mpi3snp on the example.zip file in the plink teaching material section [1]
I get the error:
```
Error in example/wgas1.tped:1: invalid nucleotide value '0' at position 265
```
I also created a jupyter notebook that can run on google colab to illustrate the issue [2]

Is this a problem from my side?

[1] https://www.cog-genomics.org/plink/1.9/resources#teach

[2] https://gist.github.com/shadiakiki1986/366a61df58475e667aa84101ff337b1a

**Comment by chponte** [comment]
Hi. Thanks for taking the time to open an issue.

I've been able to reproduce your issue. The error message points to an error in your data. Using your same data files, and after transforming the input data into the transposed format, there are loci with missing genotype information. The first occurrence happens at line 1, column 265 of the tped file, where there is a `0`. MPI3SNP does not support genotypes with missing values, and thus have to be filtered in a previous step.

Cheers,
Christian
